# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-06 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20200306_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='like',
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
