# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20200306_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
