# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20200307_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_name',
            new_name='user',
        ),
    ]
